### update an existing patient
PUT http://localhost:4000/patients/123e4567-e89b-12d3-a456-426614174000
Content-Type: application/json

{
  "name": "sumanth updated",
  "email": "xyz@gmail.com",
  "address": "123",
  "dateOfBirth": "2004-03-05"
}

###